package:
  name: "condamwe"
  version: 1.0.0

requirements:
  host:
    - python=3.9
    - pip
    - setuptools
  run:
    - python
    - pylint

source:
  path: ../condamwe

build:
  script: python setup.py install

